CD_OBJECTS     =
OBJECTS        = hello_interrupt.o
ELF_TARGET     = hello_interrupt.elf
BIN_TARGET     = hello_interrupt.bin
ADD_FILES      = 
CDOUT          = hello_interrupt_cd

include ../example.mk
