CD_OBJECTS     =
OBJECTS        = hello_plusplus.o newplusplus.o
ELF_TARGET     = hello_plusplus.elf
BIN_TARGET     = hello_plusplus.bin
ADD_FILES      = 
CDOUT          = hello_plusplus_cd

include ../example.mk
