.PHONY: all hello fxbmp fxpad cellophane psg clean

all: hello fxbmp fxpad cellophane psg

hello:
	make -C $@
fxbmp:
	make -C $@
fxpad:
	make -C $@
cellophane:
	make -C $@
psg:
	make -C $@

clean:
	make -C hello clean
	make -C fxbmp clean
	make -C fxpad clean
	make -C cellophane clean
	make -C psg clean

