.PHONY: all hello fxbmp fxpad cellophane clean

all: hello fxbmp fxpad cellophane

hello:
	make -C $@
fxbmp:
	make -C $@
fxpad:
	make -C $@
cellophane:
	make -C $@

clean:
	make -C hello clean
	make -C fxbmp clean
	make -C fxpad clean
	make -C cellophane clean

